name: Frontend CI Pipeline

on:
  push:
    branches:
      - main-dev
      - main-qa
      - main
  pull_request:
    branches:
      - main-dev
      - main-qa
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build:dev
      - run: npm run test -- --watch=false --browsers=ChromeHeadless

  build-qa:
    if: github.ref == 'refs/heads/main-qa'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build:qa

  build-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build:prod